title: Linux Config Page
description: Bookmark this to keep an eye on my project updates!
remote_theme: "mmistakes/minimal-mistakes@4.26.2"
plugins:
  - jekyll-include-cache
minimal_mistakes_skin: "dirt" #"default" "air", "aqua", "contrast", "dark", "dirt", "neon", "mint", "plum", "sunrise"
enable_copy_code_button: true
